package com.Wsdl2Code.WebServices.voto;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 11/15/2013 3:10:31 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.voto.WS_Enums.*;
import java.util.List;
import org.ksoap2.SoapEnvelope;
import org.ksoap2.SoapFault;
import org.ksoap2.serialization.SoapSerializationEnvelope;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.HeaderProperty;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import android.os.AsyncTask;
import org.ksoap2.serialization.MarshalFloat;

public class voto {
    
    public String NAMESPACE ="http://tempuri.org/";
    public String url="http://54.200.143.226/votovisible/ws/voto.asmx";
    public int timeOut = 60000;
    public IWsdl2CodeEvents eventHandler;
    public SoapProtocolVersion soapVersion;
    
    public voto(){}
    
    public voto(IWsdl2CodeEvents eventHandler)
    {
        this.eventHandler = eventHandler;
    }
    public voto(IWsdl2CodeEvents eventHandler,String url)
    {
        this.eventHandler = eventHandler;
        this.url = url;
    }
    public voto(IWsdl2CodeEvents eventHandler,String url,int timeOutInSeconds)
    {
        this.eventHandler = eventHandler;
        this.url = url;
        this.setTimeOut(timeOutInSeconds);
    }
    public void setTimeOut(int seconds){
        this.timeOut = seconds * 1000;
    }
    public void setUrl(String url){
        this.url = url;
    }
    public void putAsync(String tweeterAccount,String votacionId,String corporacion,String titulo,String url,String numero,String anio,String tweedId,String tipo,String decision,String comentario) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        putAsync(tweeterAccount, votacionId, corporacion, titulo, url, numero, anio, tweedId, tipo, decision, comentario, null);
    }
    
    public void putAsync(final String tweeterAccount,final String votacionId,final String corporacion,final String titulo,final String url,final String numero,final String anio,final String tweedId,final String tipo,final String decision,final String comentario,final List<HeaderProperty> headers) throws Exception{
        
        new AsyncTask<Void, Void, String>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected String doInBackground(Void... params) {
                return put(tweeterAccount, votacionId, corporacion, titulo, url, numero, anio, tweedId, tipo, decision, comentario, headers);
            }
            @Override
            protected void onPostExecute(String result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("put", result);
                }
            }
        }.execute();
    }
    
    public String put(String tweeterAccount,String votacionId,String corporacion,String titulo,String urlDoc,String numero,String anio,String tweedId,String tipo,String decision,String comentario){
        return put(tweeterAccount, votacionId, corporacion, titulo, urlDoc, numero, anio, tweedId, tipo, decision, comentario, null);
    }
    
    public String put(String tweeterAccount,String votacionId,String corporacion,String titulo,String urlDoc,String numero,String anio,String tweedId,String tipo,String decision,String comentario,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("http://tempuri.org/","put");
        soapReq.addProperty("tweeterAccount",tweeterAccount);
        soapReq.addProperty("votacionId",votacionId);
        soapReq.addProperty("corporacion",corporacion);
        soapReq.addProperty("titulo",titulo);
        soapReq.addProperty("url",urlDoc);
        soapReq.addProperty("numero",numero);
        soapReq.addProperty("anio",anio);
        soapReq.addProperty("tweedId",tweedId);
        soapReq.addProperty("tipo",tipo);
        soapReq.addProperty("decision",decision);
        soapReq.addProperty("comentario",comentario);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("http://tempuri.org/put", soapEnvelope,headers);
            }else{
                httpTransport.call("http://tempuri.org/put", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                        SoapPrimitive j =(SoapPrimitive) obj;
                        String resultVariable = j.toString();
                        return resultVariable;
                    }else if (obj!= null && obj instanceof String){
                        String resultVariable = (String) obj;
                        return resultVariable;
                    }
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return "";
    }
    
}
